#!/usr/bin/env bash
#
# HELPER PURPOSE
#
# Bump package version and publicly publish to npm
#

# Set error handling
set -eu -o pipefail

# HELPER COMMANDS

PRERELEASE_IDENTIFIER="-[a-z-]+"
RELEASE_TAG="latest"

if [[ $CIRCLE_TAG =~ $PRERELEASE_IDENTIFIER ]]; then RELEASE_TAG="pre-release"; fi

npm version --no-git-tag-version ${CIRCLE_TAG}
npm publish --access public --tag=${RELEASE_TAG}
