#!/usr/bin/env bash
#
# HELPER PURPOSE
#
# Run npm update to ensure npm packages in node_modules are the latest.
#
# Why we pass the flags we do to `npm update`:
#
# --dev - Also update devDependencies
#
# --no-package-lock - While we now use package-lock.json 
#   in our repos, skip package-lock.json in this instance 
#   as we're bypassing the normal npm install process     
#   and don't want to accidentally modify the file in CI.
#   Normal dependencies are still installed via `make install` 
#   which does use the package-lock.
#
# --no-save - Don't update package.json - as we don't use
#   package-lock.json, we use the checksum of package.json
#   for some CI tasks e.g. naming node_module caches
#

# Set error handling
set -eu -o pipefail

# HELPER COMMANDS

npm update --dev --no-package-lock --no-save
