#!/usr/bin/env bash
#
# HELPER PURPOSE
#
# Bump package version and publicly publish to npm
#

# Set error handling
set -eu -o pipefail

# HELPER COMMANDS

PRERELEASE_PATTERN='v[0-9]+\.[0-9]+\.[0-9]+-[a-z]+\.[0-9]+'
RELEASE_TAG="latest"

if [[ $CIRCLE_TAG =~ $PRERELEASE_PATTERN ]]; then RELEASE_TAG="pre-release"; fi

npm version --no-git-tag-version ${CIRCLE_TAG}
npm publish --access public --tag=${RELEASE_TAG}
