#!/usr/bin/env bash
#
# HELPER PURPOSE
#
# TODO: Make this example a bit more useful
#

# Set error handling
set -eu -o pipefail

# HELPER COMMANDS

echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
